dynamixel_controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10

  first_position_controller:
    type: position_controllers/JointPositionController
    joint: first

  second_position_controller:
    type: position_controllers/JointPositionController
    joint: second

dynamixel_control_hw:
  loop_frequency: 10
  cycle_time_error_threshold: 0.2
  serial_interface: /dev/ttyUSB0
  baudrate: 1000000 # in bauds
  dynamixel_timeout: 0.05 # in seconds
  dynamixel_scanning: 0.05 # in seconds
  # correspondance between hardware IDs of the actuators and their names in ROS
  hardware_mapping:
    first: 1
    second: 26
  # offset to be added, in ticks, to the position of an actuator
  hardware_corrections:
    "26": 45
  # max joint speed, in rad/s
  max_speed:
    "1": 0.1
    "26": 0.1
